name: animated_digit
description: A scroll numbers animation widget, any number that need scroll animation effects and easy to use.
version: 3.2.1
homepage: https://github.com/mingsnx/animated_digit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
